# Sets of flavor text for random pulling

PLATITUDES = [
    "Everything happens for a reason.",
    "What goes around comes around.",
    "Time heals all wounds.",
    "When one door closes, another opens.",
    "Good things come to those who wait.",
    "It is what it is.",
    "Everything will work out in the end.",
    "Tomorrow is another day.",
    "Every cloud has a silver lining.",
    "This too shall pass.",
    "Actions speak louder than words.",
    "You only live once.",
    "Live and learn.",
    "Life is what you make it.",
    "You can't have your cake and eat it too.",
    "There's no place like home.",
    "Absence makes the heart grow fonder.",
    "Better late than never.",
    "Don't judge a book by its cover.",
    "Honesty is the best policy.",
    "Practice makes perfect.",
    "The early bird catches the worm.",
    "You reap what you sow.",
    "Where there's a will, there's a way.",
    "All good things must come to an end.",
    "Rome wasn't built in a day.",
    "The grass is always greener on the other side.",
    "Out of sight, out of mind.",
    "A picture is worth a thousand words.",
    "Beggars can't be choosers.",
    "Don't count your chickens before they hatch.",
    "Every dog has its day.",
    "Great minds think alike.",
    "If it ain't broke, don't fix it.",
    "It takes two to tango.",
    "Never say never.",
    "Nothing ventured, nothing gained.",
    "Old habits die hard.",
    "The pen is mightier than the sword.",
    "There's no time like the present.",
    "When in Rome, do as the Romans do.",
    "You can't judge a book by its cover.",
    "You can't teach an old dog new tricks.",
    "A watched pot never boils.",
    "Better safe than sorry.",
    "Birds of a feather flock together.",
    "Curiosity killed the cat.",
    "Don't bite the hand that feeds you.",
    "Don't put all your eggs in one basket.",
    "Easy come, easy go.",
    "Fortune favors the bold.",
    "Haste makes waste.",
    "Ignorance is bliss.",
    "It's always darkest before the dawn.",
    "Laughter is the best medicine.",
    "Money can't buy happiness.",
    "Necessity is the mother of invention.",
    "No news is good news.",
    "One man's trash is another man's treasure.",
    "Slow and steady wins the race.",
    "The apple doesn't fall far from the tree.",
    "The best things in life are free.",
    "The squeaky wheel gets the grease.",
    "There's more than one way to skin a cat.",
    "Two wrongs don't make a right.",
    "Variety is the spice of life.",
    "When life gives you lemons, make lemonade.",
    "You can lead a horse to water, but you can't make it drink.",
    "You can't win them all.",
    "You get what you pay for.",
    "You miss 100 percent of the shots you don't take.",
    "A journey of a thousand miles begins with a single step.",
    "Actions have consequences.",
    "Everything in moderation.",
    "Give and you shall receive.",
    "Home is where the heart is.",
    "Keep calm and carry on.",
    "Knowledge is power.",
    "Learn from your mistakes.",
    "Life goes on.",
    "Look before you leap.",
    "Love conquers all.",
    "Make hay while the sun shines.",
    "Nothing lasts forever.",
    "Patience is a virtue.",
    "Silence is golden.",
    "The best is yet to come.",
    "The truth will set you free.",
    "There's a light at the end of the tunnel.",
    "Things happen for a reason.",
    "Time flies when you're having fun.",
    "To each their own.",
    "Trust the process.",
    "What doesn't kill you makes you stronger.",
    "Where there's smoke, there's fire.",
    "You can't please everyone.",
    "You can't stop the waves, but you can learn to surf.",
    "You get out what you put in.",
    "You have to crawl before you walk.",
    "You live and you learn.",
    "Everything is temporary."
]

NAMES = [
    "Avery",
    "Sage",
    "Rowan",
    "Phoenix",
    "Quinn",
    "Ellis",
    "Marlowe",
    "Indigo",
    "Lior",
    "Arden",
    "Cypress",
    "Bellamy",
    "Soren",
    "Vesper",
    "Ren",
    "Hollis",
    "Arrow",
    "Cove",
    "Indy",
    "Lark",
    "Navy",
    "Pace",
    "Roux",
    "Sparrow",
    "Zephyr"
]
